<a href="https://colab.research.google.com/github/2303A51046/AIML-2025_B/blob/main/2303A51046_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [2]:
import numpy as np
#2D Array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
#zero Array
arr3=np.zeros((3,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np
#one Array
arr4=np.ones((3,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
import numpy as np
#Range of numbers
range_arr=np.arange(0,10,2)#
print("Range Array:",range_arr)

Range Array: [0 2 4 6 8]


In [8]:
import numpy as np
#Random Array
random_arr=np.random.rand(3,3)
print("Random Array:",random_arr)

Random Array: [[0.29802305 0.48960329 0.23572116]
 [0.60438518 0.70107375 0.90782917]
 [0.45996909 0.50366961 0.24138378]]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape) #(rows,columns)
print("Dimension:",arr.ndim) #2D array
print("Data Type:",arr.dtype) #int64 or float64
print("Size:",arr.size)  #total elements
print("item size:",arr.itemsize)

shape: (2, 3)
Dimension: 2
Data Type: int64
Size: 6
item size: 8


In [14]:
import numpy as np
arr=np.array([10,20,30,40,50])
print("First element",arr[0])
print("Last element",arr[-1])
print("slice[1:4]:",arr[1:4])
print("Every second element",arr[::2])

First element 10
Last element 50
slice[1:4]: [20 30 40]
Every second element [10 30 50]


In [15]:
import numpy as np
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at row 1,col 2:",arr2[0,1])
print("second row:",arr2[1,:])
print("second column:",arr2[:,1])

element at row 1,col 2: 2
second row: [4 5 6]
second column: [2 5]


In [16]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [18]:
import numpy as np
arr=np.array([0,np.pi/2,np.pi])
print("sin values:",np.sin(arr))
print("cos values:",np.cos(arr))
print("square root",np.sqrt([1,4,9]))
print("exponential:",np.exp([1,2]))
print("logarithm:",np.log([1,np.e,np.e**2]))

sin values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos values: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
square root [1. 2. 3.]
exponential: [2.71828183 7.3890561 ]
logarithm: [0. 1. 2.]


In [21]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))
print("standard deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))

sum: 21
min: 1
max: 6
mean: 3.5
standard deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [22]:
import numpy as np
a=np.array([1,2,3])
b=5
print("add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([[4,5,6]])
print("broadcasted sum:\n:",c+d)

add scalar to array: [6 7 8]
broadcasted sum:
: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [24]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix multiplication:\n",np.dot(A,B))
print("Transpose:\n",A.T)
print("Inverse:\n",np.linalg.inv(A))
print("Determinant:\n",np.linalg.det(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:
 -2.0000000000000004


In [26]:
import numpy as np
#marks of students in 3 subjects
marks=np.array([[85,90,88],
                [78,81,85],
                [92,89,95]
                ])
print("averag marks per student",np.mean(marks,axis=1))
print("average marks per subject",np.mean(marks,axis=0))
print("highest marks in each subject",np.max(marks,axis=0))
print("lowest marks in each subject",np.min(marks,axis=0))

averag marks per student [87.66666667 81.33333333 92.        ]
average marks per subject [85.         86.66666667 89.33333333]
highest marks in each subject [92 90 95]
lowest marks in each subject [78 81 85]
